version: '3.7'

services:
  # Service pour l'API .NET
  dotnet-api:
    build:
      context: .
      dockerfile: Dockerfile.dotnet
    container_name: dotnet_container
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres-db
    networks:
      - app-network

  # Service pour PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
      POSTGRES_DB: projet_cloud_p16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  # Service pour Laravel avec Apache et PHP
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile.laravel
    container_name: laravel_container
    restart: always
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_DATABASE=projet_cloud_p16
      - DB_USERNAME=cloud
      - DB_PASSWORD=cloud
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - postgres-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
